name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eux {0}

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # You can specify the PHP version you want to use

      - name: Install Composer dependencies
        run: composer install

      - name: PHP lint
        run: php -l .

      - name: PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: PHP Mess Detector
        run: vendor/bin/phpmd . text phpmd.xml

      - name: PHP Code Beautifier and Fixer
        run: vendor/bin/phpcbf
        continue-on-error: true
