name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Composer dependencies
        run: composer install

      - name: PHP lint
        run: php -l .

      - name: PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: PHP Mess Detector
        run: vendor/bin/phpmd . text phpmd.xml

      - name: PHP Code Beautifier and Fixer
        run: vendor/bin/phpcbf
        continue-on-error: true
