name: PHP Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php_code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # You can specify the PHP version you want to use

      - name: Install Composer Dependencies
        run: composer install

      - name: PHP Lint
        run: php -l .

      - name: PHP CodeSniffer (PHPCS)
        run: ./vendor/bin/phpcs --standard=PSR12 .

      - name: PHP Mess Detector (PHPMD)
        run: ./vendor/bin/phpmd . text index.php
        
      - name: PHP Code Beautifier and Fixer (PHPCBF)
        run: ./vendor/bin/phpcbf --standard=PSR12 index.php
        
      
